
// MUI Imports

import Typography from '@mui/material/Typography'




const PrivacyPolicy = () => {
  return (
    <div className='flex flex-col gap-6'>
      <div className='flex flex-col justify-center items-center gap-2'>
        <Typography variant='h4'>Privacy Policy</Typography>
        <Typography variant='body2'>Last updated: August 22, 2024</Typography>
      </div>
      <Typography>
        This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </Typography>
      <Typography>
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" rel="noopener noreferrer">Privacy Policy Generator</a>.
      </Typography>

      <Typography variant='h5'>Interpretation and Definitions</Typography>
      <Typography variant='h6'>Interpretation</Typography>
      <Typography>
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </Typography>

      <Typography variant='h6'>Definitions</Typography>
      <Typography>For the purposes of this Privacy Policy:</Typography>
      <ul className='list-disc pl-6'>
        <li><Typography><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</Typography></li>
        <li><Typography><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</Typography></li>
        <li><Typography><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot;, or &quot;Our&quot; in this Agreement) refers to Botployment SA, 200 mts norte sobre el puente rio sarchi.</Typography></li>
        <li><Typography><strong>Cookies</strong> are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.</Typography></li>
        <li><Typography><strong>Country</strong> refers to: Costa Rica</Typography></li>
        <li><Typography><strong>Device</strong> means any device that can access the Service, such as a computer, a cellphone, or a digital tablet.</Typography></li>
        <li><Typography><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</Typography></li>
        <li><Typography><strong>Service</strong> refers to the Website.</Typography></li>
        <li><Typography><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.</Typography></li>
        <li><Typography><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</Typography></li>
        <li><Typography><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</Typography></li>
        <li><Typography><strong>Website</strong> refers to Botployment, accessible from <a href="https://botployment.com" rel="external nofollow noopener" target="_blank">https://botployment.com</a></Typography></li>
        <li><Typography><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</Typography></li>
      </ul>

      <Typography variant='h5'>Collecting and Using Your Personal Data</Typography>
      <Typography variant='h6'>Types of Data Collected</Typography>
      <Typography variant='h6'>Personal Data</Typography>
      <Typography>
        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
      </Typography>
      <ul className='list-disc pl-6'>
        <li><Typography>Email address</Typography></li>
        <li><Typography>First name and last name</Typography></li>
        <li><Typography>Phone number</Typography></li>
        <li><Typography>Address, State, Province, ZIP/Postal code, City</Typography></li>
        <li><Typography>Usage Data</Typography></li>
      </ul>
    </div>
  )
}

export default PrivacyPolicy
